backend:
  name: git-gateway
  branch: main

locale: "es"

media_folder: ""
public_folder: "/"

collections:
  - name: "productos"
    label: "Productos"
    label_singular: "Producto"
    files:
      - name: "catalogo"
        label: "Catalogo de productos"
        file: "productos.json"
        fields:
          - label: "Productos"
            name: "productos"
            widget: "list"
            summary: "{{fields.titulo}} - {{fields.cat}}"
            fields:
              - label: "Categoria"
                name: "cat"
                widget: "select"
                options:
                  - "Tortas"
                  - "Tartas"
                  - "Box Celebracion"
                  - "Cuadrados 8x8 cm"
                  - "Minicakes"
                  - "Alfajores"
                  - "Cookies"
                  - "Panificados"
                  - "Facturas"
              - label: "Titulo"
                name: "titulo"
                widget: "string"
              - label: "Descripcion"
                name: "desc"
                widget: "text"
              - label: "Foto"
                name: "file"
                widget: "image"
